export const SET_LOADING = "SET_LOADING";
export const SET_TODO_TITLE = "SET_TODO_TITLE";
export const CLEAR_TODO_TITLE = "CLEAR_TODO_TITLE";
export const CREATE_TODO = "CREATE_TODO";
export const GET_TODOS = "GET_TODOS";
export const REMOVE_TODO = "REMOVE_TODO";

export const CREATE_TODO_REQUESTED = "CREATE_TODO_REQUESTED";
export const GET_TODOS_REQUESTED = "GET_TODOS_REQUESTED";
export const REMOVE_TODO_REQUESTED = "REMOVE_TODO_REQUESTED";
